### ISSUE TITLE
error on update.py file = KeyError

### ISSUE THREAD

**Issue by pfolcato** [jamesremuscat/pyze#110]
I have this error when I launch update.py:
Traceback (most recent call last):
  File "update.py", line 93, in <module>
    Main().execute()
  File "update.py", line 66, in execute
    if batt['lastUpdateTime'] != lastUpdateTime:
KeyError: 'lastUpdateTime'

What can I do?
if I write pyze status --vin VFXXXXXXXXXX
I can see all the correct info of my car....

**Comment by jamesremuscat** [comment]
There is no `update.py` within `pyze`.

Please report this error to the author of the `update.py` file, as it looks like they're making an assumption about the presence of `lastUpdateTime` in their code.
