### ISSUE TITLE
Can't log in anymore since one week (january 2023)

### ISSUE THREAD

**Issue by RalfJahns** [jamesremuscat/pyze#112]
Hello,

I only get this error message:
Error communicating with Renault API!
{"error":"access_denied","error_description":"Unauthorized"}

I didn't check if the keys changed and did the steps to update the kameron and the gigya key anyway, but this didn't help.
I use pyze in connection with my diy EVSE and it would be a pity, if it doesn't work anymore. 
The "My Renault" app is working.

Can anybody confirm if it is working or not?

Best regards
Ralf

**Comment by jamesremuscat** [comment]
Working for me; current Kamereon API key is `VAX7...7Ss`, and Gigya API key is `3_e8d...wuxz`.
