### ISSUE TITLE
Make a PIP package

### ISSUE THREAD

**Issue by epenet** [jamesremuscat/pyze#2]
Are you planning to publish a PIP module?

**Comment by jamesremuscat** [comment]
Have just published PyZE 0.1.0 to PyPI.

**Comment by jamesremuscat** [comment]
... but I messed up something with the packaging, so that'll be broken for you. Please stand by, caller... :slightly_smiling_face:

**Comment by jamesremuscat** [comment]
OK, PyZE `0.1.1` released to PyPI and confirmed as working.
