### ISSUE TITLE
Investigate alternative URLs

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/pyze#34]
Just discovered a bunch of alternative URLs for API endpoints.

Whereas previously, vehicle endpoints were at
```
/commerce/v1/accounts/kmr/remote-services/car-adapter/v<VERSION>/cars/<VIN>/<ENDPOINT>
```
it appears a very similar set of endpoints are available at
```
/commerce/v1/accounts/<ACCOUNTID>/kamereon/kca/car-adapter/v<VERSION>/cars/<VIN>/<ENDPOINT>
```
and it is the latter that are used by the more recent versions of the app.

It seems that the `country` parameter must be specified for all URLs in the latter form.

I don't know if this is significant, or just a waste of time.

**Comment by g-mocken** [comment]
As of today, the old style endpoints no longer work (for me).

**Comment by neutrino85** [comment]
No longer work for me too. And very unstable since yesterday.

**Comment by mfonville** [comment]
I just wanted to give a heads-up that Renault has changed from localized My Renault-apps (that differed per country) to a single app for every user in every country: https://play.google.com/store/apps/details?id=com.renault.myrenault.one.fr&authuser=0

Maybe they also changed some API stuff with this new release.
