### ISSUE TITLE
Internal Server Error code:500 with stats (ac or charge)

### ISSUE THREAD

**Issue by sumoo13** [jamesremuscat/pyze#35]
hi,
have you the same error 
when i test in cli :
pyze charge-stats or pyze ac-stats
i get an Internal Server Error code:500 !

**Comment by jamesremuscat** [comment]
`ac-stats` works for me, but `charge-stats` is broken on Renault's end and has been for a little while.

What's the full error message you get from `ac-stats`?

**Comment by sumoo13** [comment]
full message error
Error communicating with Renault API!
{"errors":[{"status":"Internal Server Error","code":"500","title":"Unexpected error","detail":"Invalid response from the upstream server (The request sent to the GDC is erroneous) ; 502 Bad Gateway"}]}

**Comment by jamesremuscat** [comment]
Yes, I'm afraid that's a problem with Renault's servers. There's nothing that pyze can do about it.
