### ISSUE TITLE
Status not working when totalMileage is missing in "cockpit" response

### ISSUE THREAD

**Issue by g-mocken** [jamesremuscat/pyze#37]
"pyze status" no longer works (login and other subcommands are still okay). It did work for me before. As it appears, the "cockpit" server response has empty attributes (totalMileage is missing) and pyze cannot cope with that.

`DEBUG:urllib3.connectionpool:https://api-wired-prod-1-euw1.wrd-aws.com:443 "GET /commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/Vxxxxx/cockpit HTTP/1.1" 200 None
DEBUG:pyze.api.kamereon:Received Kamereon vehicle response: {'data': {'type': 'Car', 'id': 'Vxxxxx', 'attributes': {}}}
Traceback (most recent call last):
  File "/usr/local/bin/pyze", line 11, in <module>
    load_entry_point('PyZE==0.3.0', 'console_scripts', 'pyze')()
  File "/usr/local/lib/python3.7/site-packages/PyZE-0.3.0-py3.7.egg/pyze/cli/__main__.py", line 68, in main
  File "/usr/local/lib/python3.7/site-packages/PyZE-0.3.0-py3.7.egg/pyze/cli/status.py", line 62, in run
TypeError: unsupported operand type(s) for /: 'str' and 'float'
`

This may not be a software change on the server, but simply due to my car not being reachable for a couple of days. The old ZE api was also known to omit some fields when no recent data was available. So this problem may go away when I use the car tomorrow - but will come back the next weekend or so.

**Comment by jamesremuscat** [comment]
Thanks for the bug report. I've also added this to the [list of issues with the API](https://github.com/jamesremuscat/pyze/wiki/Known-issues-with-the-Renault-API) on the wiki, and pushed a commit that should fix the problem on pyze's end.
