### ISSUE TITLE
ZE50 Endpoint error

### ISSUE THREAD

**Issue by sumoo13** [jamesremuscat/pyze#40]
not really an issue, just an information
I noticed that there were some errors with hvac endpoint and charge endpoint with ze50

> /hvac-status?country=FR): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway

> charges?start=20200101&end=20200210&country=FR): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

some people with ze50 are the same error ?

**Comment by neutrino85** [comment]
Same error here.

**Comment by jamesremuscat** [comment]
Thanks for the info.

The first of those looks like a transient error on Renault's side; it might sort itself out in time.

As for the second: if that doesn't go away, be sure you have _both_ ZE Services subscriptions active on your account. That's an endpoint that Renault seem to be tinkering with quite a lot, so it's worth trying again later. (I seem to be saying that a lot with Renault's API...)
