### ISSUE TITLE
V2 Cokpit status API

### ISSUE THREAD

**Issue by sumoo13** [jamesremuscat/pyze#50]
New endpoint (GET): car-adapter/v2/cars/{vin}/cockpit.

Example response:
`[data] => Array
        (
            [type] => Car
            [id] => VF1BG000155836384
            [attributes] => Array
                (
                    [totalMileage] => 5134.08
                )
        )`
just add 2 decimal ...

**Comment by MattCheetham** [comment]
Awesome, thanks for finding this one. Was frustrating me that my reading was sometime a little bit out. Presumably due to rounding!

**Comment by mfonville** [comment]
Great find, a PR for this would be trivial:
```
    def mileage(self):
        return self._get('cockpit', version=2)
```
