### ISSUE TITLE
Renault API has stopped working! Change required.

### ISSUE THREAD

**Issue by Dave-09** [jamesremuscat/pyze#75]
The Kameron token was removed from requests. Can you make a fix?

Thank you!

**Comment by MattCheetham** [comment]
Duplicate of issue #73 and has already been fixed in pull request #74.

**Comment by Dave-09** [comment]
Excuses! I had not looked at the FIXED option.

**Comment by roberthunt** [comment]
@MattCheetham I guess this is the same reason that Zeddy can no longer login, will a new version be required to fix it?

**Comment by MattCheetham** [comment]
@roberthunt Yup. See https://github.com/MattCheetham/zeddy-support/issues/10
