### ISSUE TITLE
ModuleNotFoundError: No module named 'pyze'

### ISSUE THREAD

**Issue by sahilsdei** [jamesremuscat/pyze#8]
I am trying to import it in my flask app but getting error of ModuleNotFoundError: No module named 'pyze'.
when i clone the github repository and run it as stand alone it's cli version is working fine.
Installed using pipenv on python version 3.7.1

**Comment by jamesremuscat** [comment]
All the usual questions: are you sure your Flask app is using the correct virtualenv? And that you've definitely installed PyZE into it rather than somewhere else by accident?

**Comment by jamesremuscat** [comment]
OP went away.
