### ISSUE TITLE
PyZE doesn't always receive new datapoints, while the MyRenault app does

### ISSUE THREAD

**Issue by mfonville** [jamesremuscat/pyze#91]
This week both my Zoe ZE50 and the MyRenault app of my phone received an update.
PyZE  doesn't get any more up-to-date telemetry information, but MyRenault app works fine :-/.

How can we reverse engineer any changes that Renault has made? @jamesremuscat

**Comment by edddeduck** [comment]
I have an automated system running and it's updating as expected & I can see my driving odometer update from this morning and the battery drop.

UK Based cars testing on one ZE50 and one ZE 40 vehicle.

**Comment by mfonville** [comment]
Hmm, so weird.
Also it seemed for me to go phased. First PyZE still reported some values, if I opened the MyRenault app to update, it would also make that value available to PyZE. But at the moment it doesn't get any value anymore.

My car is The Netherlands.

@edddeduck did your ZE50 already got the "283C30559R" system update that is available since the start of this week?

**Comment by mfonville** [comment]
Hmm, another single telemetry point came through again at 14:17 CET (after I had opened the MyRenault app on my phone)
It is really weird...

**Comment by mfonville** [comment]
I am getting some more telemetry datapoints now even without using the app.

Still it is weird though (and can't find an explanation at this moment) why throughout the day I could get updates on the app, while the PyZE scripts did not get those. :-/

**Comment by mfonville** [comment]
Ok, I decompiled the latest MyRenault app and don't see any changes in the API.
So can't explain really why this happened, maybe AWS problems or so. I will close it and just hope it doesn't happen again...
