### ISSUE TITLE
Error communicating with Renault API!

### ISSUE THREAD

**Issue by plin2** [jamesremuscat/pyze#94]
Hi,

I'm getting an error message when I start pyze:

Error communicating with Renault API!
{"error":"access_denied","error_description":"Unauthorized"}

Did Renault change the API or did the API keys get invalidated`?

**Comment by db-EV** [comment]
See [Error 403 on person](https://github.com/hacf-fr/renault-api/issues/181)

**Comment by plin2** [comment]
New KAMERON API Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2 works for me. Where do you find it? 

I tried the keys obtained through 
https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_en_GB.json
but they didn't work.

**Comment by db-EV** [comment]
Se [https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7#gistcomment-3615860](https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7#gistcomment-3615860) and below.

**Comment by plin2** [comment]
new key works, will follow the other thread

**Comment by plin2** [comment]
new key works, will follow the other thread

**Comment by jumpjack** [comment]
Key changed again with recent app update? (21/2/2022)

**Comment by plin2** [comment]
I have access problems as well:
{"error":"access_denied","error_description":"Unauthorized"}

**Comment by jumpjack** [comment]
I just replicated the issue also in my own app and in https://github.com/hacf-fr/renault-api , hence it's not a pyze bug.

**Comment by plin2** [comment]
I tried to get fresh keys from https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_en_DE.json and extracted the "wiredProd" and "gigyaProd" apikeys - didn't help. My RenaultZE App seams to work.

**Comment by db-EV** [comment]
I think it's a new Kamereon API key we need. This one is hardcoded in the app if I remember correct.

**Comment by db-EV** [comment]
See https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7?permalink_comment_id=4100284#gistcomment-4100284 for new Kamereon API key.

**Comment by plin2** [comment]
The new KAMEREON API Key is **VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss**

**Comment by plin2** [comment]
The new KAMEREON API Key is **VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss**

**Comment by jumpjack** [comment]
new key?
app updated on 26/2.

**Comment by db-EV** [comment]
No, ZoePHP and HA still working.
